# The URL the site will be built for
base_url = "https://kattila.linkkijkl.fi"

default_language = "fi"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[languages.fi.translations]
dark = "Tumma"
fetching = "Haetaan"
header_title = "Kattilan kahvikamera"
in_kattila = "Kattilassa paikalla"
interested = "Halukkaat"
light = "Vaalea"
more_elsewhere = "Sivustosta muualla"
phone_app = "Puhelinsovellus"
site_features = "Sivun ominaisuudet"
system = "Järjestelmä"
want_coffee = "Haluan kahvia"

[languages.en.translations]
dark = "Dark"
fetching = "Fetching"
header_title = "Kattila coffeecam"
in_kattila = "In Kattila"
interested = "Interested"
light = "Light"
more_elsewhere = "More elsewhere"
phone_app  = "Phone app"
site_features = "Site features"
system = "System"
want_coffee = "I want coffee"
